// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToeicGenius.Repositories.Persistence;

#nullable disable

namespace ToeicGenius.Migrations
{
    [DbContext(typeof(ToeicGeniusDbContext))]
    [Migration("20251001091927_AddDatabaseV1.0")]
    partial class AddDatabaseV10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestParts", b =>
                {
                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.HasKey("TestId", "PartId");

                    b.HasIndex("PartId");

                    b.ToTable("TestParts");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.AIFeedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("AIScorer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("UserAnswerId")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.HasIndex("UserAnswerId");

                    b.ToTable("AIFeedbacks");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Flashcard", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SetId")
                        .HasColumnType("int");

                    b.HasKey("CardId");

                    b.HasIndex("SetId");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.FlashcardProgress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgressId"));

                    b.Property<int>("FlashcardId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProgressId");

                    b.HasIndex("FlashcardId");

                    b.ToTable("FlashcardProgresses");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.FlashcardSet", b =>
                {
                    b.Property<int>("SetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SetId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SetId");

                    b.HasIndex("UserId");

                    b.ToTable("FlashcardSets");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Option", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptionId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OptionLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OptionOrder")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("OptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            OptionId = 1,
                            Content = "Paris",
                            IsCorrect = true,
                            OptionLabel = "A",
                            OptionOrder = 0,
                            QuestionId = 1
                        },
                        new
                        {
                            OptionId = 2,
                            Content = "London",
                            IsCorrect = false,
                            OptionLabel = "B",
                            OptionOrder = 0,
                            QuestionId = 1
                        },
                        new
                        {
                            OptionId = 3,
                            Content = "Berlin",
                            IsCorrect = false,
                            OptionLabel = "C",
                            OptionOrder = 0,
                            QuestionId = 1
                        },
                        new
                        {
                            OptionId = 4,
                            Content = "Madrid",
                            IsCorrect = false,
                            OptionLabel = "D",
                            OptionOrder = 0,
                            QuestionId = 1
                        });
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Part", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartNumber")
                        .HasColumnType("int");

                    b.Property<int>("Skill")
                        .HasColumnType("int");

                    b.HasKey("PartId");

                    b.ToTable("Parts");

                    b.HasData(
                        new
                        {
                            PartId = 1,
                            Description = "Listening – Photographs",
                            Name = "Part 1",
                            PartNumber = 1,
                            Skill = 0
                        },
                        new
                        {
                            PartId = 2,
                            Description = "Listening – Question-Response",
                            Name = "Part 2",
                            PartNumber = 2,
                            Skill = 0
                        },
                        new
                        {
                            PartId = 3,
                            Description = "Listening – Conversations",
                            Name = "Part 3",
                            PartNumber = 3,
                            Skill = 0
                        },
                        new
                        {
                            PartId = 4,
                            Description = "Listening – Talks",
                            Name = "Part 4",
                            PartNumber = 4,
                            Skill = 0
                        },
                        new
                        {
                            PartId = 5,
                            Description = "Reading – Incomplete Sentences",
                            Name = "Part 5",
                            PartNumber = 5,
                            Skill = 0
                        },
                        new
                        {
                            PartId = 6,
                            Description = "Reading – Text Completion",
                            Name = "Part 6",
                            PartNumber = 6,
                            Skill = 0
                        },
                        new
                        {
                            PartId = 7,
                            Description = "Reading – Reading Comprehension",
                            Name = "Part 7",
                            PartNumber = 7,
                            Skill = 0
                        },
                        new
                        {
                            PartId = 8,
                            Description = "Writing – Câu 1-5",
                            Name = "Part 1",
                            PartNumber = 1,
                            Skill = 2
                        },
                        new
                        {
                            PartId = 9,
                            Description = "Writing – Câu 6-7",
                            Name = "Part 2",
                            PartNumber = 2,
                            Skill = 2
                        },
                        new
                        {
                            PartId = 10,
                            Description = "Writing – Câu 8",
                            Name = "Part 3",
                            PartNumber = 3,
                            Skill = 2
                        },
                        new
                        {
                            PartId = 11,
                            Description = "Speaking – Câu 1-2",
                            Name = "Part 1",
                            PartNumber = 1,
                            Skill = 1
                        },
                        new
                        {
                            PartId = 12,
                            Description = "Speaking – Câu 3-4",
                            Name = "Part 2",
                            PartNumber = 2,
                            Skill = 1
                        },
                        new
                        {
                            PartId = 13,
                            Description = "Speaking – Câu 5-7",
                            Name = "Part 3",
                            PartNumber = 3,
                            Skill = 1
                        },
                        new
                        {
                            PartId = 14,
                            Description = "Speaking – Câu 8-10",
                            Name = "Part 4",
                            PartNumber = 4,
                            Skill = 1
                        },
                        new
                        {
                            PartId = 15,
                            Description = "Speaking – Câu 11",
                            Name = "Part 5",
                            PartNumber = 5,
                            Skill = 1
                        });
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionGroupId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionTypeId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.HasIndex("PartId");

                    b.HasIndex("QuestionGroupId");

                    b.HasIndex("QuestionTypeId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 2,
                            Content = "Single Question 2",
                            Number = 2,
                            PartId = 1,
                            QuestionTypeId = 1
                        },
                        new
                        {
                            QuestionId = 3,
                            Content = "Single Question 3",
                            Number = 3,
                            PartId = 2,
                            QuestionTypeId = 2
                        },
                        new
                        {
                            QuestionId = 4,
                            Content = "Single Question 4",
                            Number = 4,
                            PartId = 2,
                            QuestionTypeId = 2
                        },
                        new
                        {
                            QuestionId = 5,
                            Content = "Single Question 5",
                            Number = 5,
                            PartId = 1,
                            QuestionTypeId = 1
                        },
                        new
                        {
                            QuestionId = 6,
                            Content = "Single Question 6",
                            Number = 6,
                            PartId = 1,
                            QuestionTypeId = 1
                        },
                        new
                        {
                            QuestionId = 7,
                            Content = "Single Question 7",
                            Number = 7,
                            PartId = 2,
                            QuestionTypeId = 2
                        },
                        new
                        {
                            QuestionId = 8,
                            Content = "Single Question 8",
                            Number = 8,
                            PartId = 2,
                            QuestionTypeId = 2
                        },
                        new
                        {
                            QuestionId = 9,
                            Content = "Single Question 9",
                            Number = 9,
                            PartId = 1,
                            QuestionTypeId = 1
                        },
                        new
                        {
                            QuestionId = 10,
                            Content = "Single Question 10",
                            Number = 10,
                            PartId = 1,
                            QuestionTypeId = 1
                        },
                        new
                        {
                            QuestionId = 11,
                            Content = "Group 1 - Question 1",
                            Number = 1,
                            PartId = 1,
                            QuestionGroupId = 1,
                            QuestionTypeId = 1
                        },
                        new
                        {
                            QuestionId = 12,
                            Content = "Group 1 - Question 2",
                            Number = 2,
                            PartId = 1,
                            QuestionGroupId = 1,
                            QuestionTypeId = 1
                        },
                        new
                        {
                            QuestionId = 13,
                            Content = "Group 1 - Question 3",
                            Number = 3,
                            PartId = 1,
                            QuestionGroupId = 1,
                            QuestionTypeId = 1
                        },
                        new
                        {
                            QuestionId = 14,
                            Content = "Group 2 - Question 1",
                            Number = 1,
                            PartId = 2,
                            QuestionGroupId = 2,
                            QuestionTypeId = 2
                        },
                        new
                        {
                            QuestionId = 15,
                            Content = "Group 2 - Question 2",
                            Number = 2,
                            PartId = 2,
                            QuestionGroupId = 2,
                            QuestionTypeId = 2
                        },
                        new
                        {
                            QuestionId = 16,
                            Content = "Group 2 - Question 3",
                            Number = 3,
                            PartId = 2,
                            QuestionGroupId = 2,
                            QuestionTypeId = 2
                        },
                        new
                        {
                            QuestionId = 17,
                            Content = "Group 3 - Question 1",
                            Number = 1,
                            PartId = 1,
                            QuestionGroupId = 3,
                            QuestionTypeId = 1
                        },
                        new
                        {
                            QuestionId = 18,
                            Content = "Group 3 - Question 2",
                            Number = 2,
                            PartId = 1,
                            QuestionGroupId = 3,
                            QuestionTypeId = 1
                        },
                        new
                        {
                            QuestionId = 19,
                            Content = "Group 3 - Question 3",
                            Number = 3,
                            PartId = 1,
                            QuestionGroupId = 3,
                            QuestionTypeId = 1
                        },
                        new
                        {
                            QuestionId = 1,
                            Content = "What is the capital of France?",
                            Number = 1,
                            PartId = 1,
                            QuestionTypeId = 1
                        });
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.QuestionGroup", b =>
                {
                    b.Property<int>("QuestionGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionGroupId"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<string>("PassageContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassageType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionGroupId");

                    b.HasIndex("PartId");

                    b.ToTable("QuestionGroups");

                    b.HasData(
                        new
                        {
                            QuestionGroupId = 1,
                            OrderIndex = 0,
                            PartId = 6,
                            PassageContent = "Passage1"
                        },
                        new
                        {
                            QuestionGroupId = 2,
                            OrderIndex = 0,
                            PartId = 7,
                            PassageContent = "Passage2"
                        },
                        new
                        {
                            QuestionGroupId = 3,
                            OrderIndex = 0,
                            PartId = 7,
                            PassageContent = "Passage3"
                        });
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.QuestionType", b =>
                {
                    b.Property<int>("QuestionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionTypeId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skill")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionTypeId");

                    b.ToTable("QuestionTypes");

                    b.HasData(
                        new
                        {
                            QuestionTypeId = 1,
                            Description = "Part 1 – Photographs",
                            Skill = "Listening",
                            TypeName = "MCQ"
                        },
                        new
                        {
                            QuestionTypeId = 2,
                            Description = "Part 2 – Question-Response",
                            Skill = "Listening",
                            TypeName = "MCQ"
                        },
                        new
                        {
                            QuestionTypeId = 3,
                            Description = "Part 3 – Conversations",
                            Skill = "Listening",
                            TypeName = "MCQ"
                        },
                        new
                        {
                            QuestionTypeId = 4,
                            Description = "Part 4 – Talks",
                            Skill = "Listening",
                            TypeName = "MCQ"
                        },
                        new
                        {
                            QuestionTypeId = 5,
                            Description = "Part 5 – Incomplete Sentences",
                            Skill = "Reading",
                            TypeName = "MCQ"
                        },
                        new
                        {
                            QuestionTypeId = 6,
                            Description = "Part 6 – Text Completion",
                            Skill = "Reading",
                            TypeName = "MCQ"
                        },
                        new
                        {
                            QuestionTypeId = 7,
                            Description = "Part 7 – Reading Comprehension",
                            Skill = "Reading",
                            TypeName = "MCQ"
                        },
                        new
                        {
                            QuestionTypeId = 8,
                            Description = "Speaking – Short Answer / Read Aloud / Respond to Question",
                            Skill = "Speaking",
                            TypeName = "ShortAnswer"
                        },
                        new
                        {
                            QuestionTypeId = 9,
                            Description = "Writing – Sentence / Paragraph / Email Writing",
                            Skill = "Writing",
                            TypeName = "Essay"
                        });
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("RevokeAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokeByIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "User"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "TestCreator"
                        });
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.SolutionDetail", b =>
                {
                    b.Property<int>("SolutionDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolutionDetailId"));

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("SolutionDetailId");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.ToTable("SolutionDetails");

                    b.HasData(
                        new
                        {
                            SolutionDetailId = 1,
                            Explanation = "Paris is the capital of France.",
                            QuestionId = 1
                        });
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("TestMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.UserAnswer", b =>
                {
                    b.Property<int>("UserAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAnswerId"));

                    b.Property<string>("AnswerAudioUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OptionId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("UserTestId")
                        .HasColumnType("int");

                    b.HasKey("UserAnswerId");

                    b.HasIndex("OptionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserTestId");

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.UserOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtpCodeHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UserOtps");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.UserTest", b =>
                {
                    b.Property<int>("UserTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserTestId"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<string>("TestMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserTestId");

                    b.HasIndex("TestId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTests");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.UserTestSkillScore", b =>
                {
                    b.Property<int>("UserTestResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserTestResultId"));

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Skill")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserTestId")
                        .HasColumnType("int");

                    b.HasKey("UserTestResultId");

                    b.HasIndex("UserTestId");

                    b.ToTable("UserTestSkillScores");
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("TestParts", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.Part", null)
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToeicGenius.Domains.Entities.Test", null)
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.AIFeedback", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.UserAnswer", "UserAnswer")
                        .WithMany()
                        .HasForeignKey("UserAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAnswer");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Flashcard", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.FlashcardSet", "FlashcardSet")
                        .WithMany("Flashcards")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlashcardSet");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.FlashcardProgress", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.Flashcard", "Flashcard")
                        .WithMany("Progresses")
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flashcard");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.FlashcardSet", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Option", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Question", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.Part", "Part")
                        .WithMany("Questions")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ToeicGenius.Domains.Entities.QuestionGroup", "QuestionGroup")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionGroupId");

                    b.HasOne("ToeicGenius.Domains.Entities.QuestionType", "QuestionType")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("QuestionGroup");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.QuestionGroup", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.Part", "Part")
                        .WithMany("QuestionGroups")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.RefreshToken", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.SolutionDetail", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.Question", "Question")
                        .WithOne("SolutionDetail")
                        .HasForeignKey("ToeicGenius.Domains.Entities.SolutionDetail", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.UserAnswer", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.Option", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId");

                    b.HasOne("ToeicGenius.Domains.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToeicGenius.Domains.Entities.UserTest", "UserTest")
                        .WithMany("UserAnswers")
                        .HasForeignKey("UserTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");

                    b.Navigation("Question");

                    b.Navigation("UserTest");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.UserTest", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.Test", "Test")
                        .WithMany("UserTests")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToeicGenius.Domains.Entities.User", "User")
                        .WithMany("UserTests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.UserTestSkillScore", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.UserTest", "UserTest")
                        .WithMany("SkillScores")
                        .HasForeignKey("UserTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserTest");
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToeicGenius.Domains.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Flashcard", b =>
                {
                    b.Navigation("Progresses");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.FlashcardSet", b =>
                {
                    b.Navigation("Flashcards");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Part", b =>
                {
                    b.Navigation("QuestionGroups");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Question", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("SolutionDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.QuestionGroup", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.QuestionType", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Test", b =>
                {
                    b.Navigation("UserTests");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserTests");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.UserTest", b =>
                {
                    b.Navigation("SkillScores");

                    b.Navigation("UserAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
