// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToeicGenius.Repositories.Persistence;

#nullable disable

namespace ToeicGenius.Migrations
{
    [DbContext(typeof(ToeicGeniusDbContext))]
    partial class ToeicGeniusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToeicGenius.Domains.Entities.AIFeedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("AIScorer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserAnswerId")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.HasIndex("UserAnswerId");

                    b.ToTable("AIFeedbacks");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Flashcard", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SetId")
                        .HasColumnType("int");

                    b.HasKey("CardId");

                    b.HasIndex("SetId");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.FlashcardProgress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgressId"));

                    b.Property<int>("FlashcardId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProgressId");

                    b.HasIndex("FlashcardId");

                    b.ToTable("FlashcardProgresses");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.FlashcardSet", b =>
                {
                    b.Property<int>("SetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SetId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SetId");

                    b.HasIndex("UserId");

                    b.ToTable("FlashcardSets");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Option", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptionId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("OptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            OptionId = 1,
                            Content = "Paris",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4797),
                            IsCorrect = true,
                            Label = "A",
                            QuestionId = 1,
                            Status = 1
                        },
                        new
                        {
                            OptionId = 2,
                            Content = "London",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4798),
                            IsCorrect = false,
                            Label = "B",
                            QuestionId = 1,
                            Status = 1
                        },
                        new
                        {
                            OptionId = 3,
                            Content = "Berlin",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4799),
                            IsCorrect = false,
                            Label = "C",
                            QuestionId = 1,
                            Status = 1
                        },
                        new
                        {
                            OptionId = 4,
                            Content = "Madrid",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4800),
                            IsCorrect = false,
                            Label = "D",
                            QuestionId = 1,
                            Status = 1
                        },
                        new
                        {
                            OptionId = 5,
                            Content = "Paris",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4801),
                            IsCorrect = true,
                            Label = "A",
                            QuestionId = 11,
                            Status = 1
                        },
                        new
                        {
                            OptionId = 6,
                            Content = "London",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4802),
                            IsCorrect = false,
                            Label = "B",
                            QuestionId = 11,
                            Status = 1
                        },
                        new
                        {
                            OptionId = 7,
                            Content = "Berlin",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4803),
                            IsCorrect = false,
                            Label = "C",
                            QuestionId = 11,
                            Status = 1
                        },
                        new
                        {
                            OptionId = 8,
                            Content = "Madrid",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4804),
                            IsCorrect = false,
                            Label = "D",
                            QuestionId = 11,
                            Status = 1
                        });
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Part", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartNumber")
                        .HasColumnType("int");

                    b.Property<int>("Skill")
                        .HasColumnType("int");

                    b.HasKey("PartId");

                    b.ToTable("Parts");

                    b.HasData(
                        new
                        {
                            PartId = 1,
                            Description = "Listening – Photographs",
                            Name = "Part 1",
                            PartNumber = 1,
                            Skill = 0
                        },
                        new
                        {
                            PartId = 2,
                            Description = "Listening – Question-Response",
                            Name = "Part 2",
                            PartNumber = 2,
                            Skill = 0
                        },
                        new
                        {
                            PartId = 3,
                            Description = "Listening – Conversations",
                            Name = "Part 3",
                            PartNumber = 3,
                            Skill = 0
                        },
                        new
                        {
                            PartId = 4,
                            Description = "Listening – Talks",
                            Name = "Part 4",
                            PartNumber = 4,
                            Skill = 0
                        },
                        new
                        {
                            PartId = 5,
                            Description = "Reading – Incomplete Sentences",
                            Name = "Part 5",
                            PartNumber = 5,
                            Skill = 0
                        },
                        new
                        {
                            PartId = 6,
                            Description = "Reading – Text Completion",
                            Name = "Part 6",
                            PartNumber = 6,
                            Skill = 0
                        },
                        new
                        {
                            PartId = 7,
                            Description = "Reading – Reading Comprehension",
                            Name = "Part 7",
                            PartNumber = 7,
                            Skill = 0
                        },
                        new
                        {
                            PartId = 8,
                            Description = "Writing – Write a sentence based on a picture",
                            Name = "Part 1",
                            PartNumber = 1,
                            Skill = 2
                        },
                        new
                        {
                            PartId = 9,
                            Description = "Writing – Respond to a written request",
                            Name = "Part 2",
                            PartNumber = 2,
                            Skill = 2
                        },
                        new
                        {
                            PartId = 10,
                            Description = "Writing – Write an opinion essay",
                            Name = "Part 3",
                            PartNumber = 3,
                            Skill = 2
                        },
                        new
                        {
                            PartId = 11,
                            Description = "Speaking – Read a text aloud",
                            Name = "Part 1",
                            PartNumber = 1,
                            Skill = 1
                        },
                        new
                        {
                            PartId = 12,
                            Description = "Speaking – Describe a picture",
                            Name = "Part 2",
                            PartNumber = 2,
                            Skill = 1
                        },
                        new
                        {
                            PartId = 13,
                            Description = "Speaking – Respond to questions",
                            Name = "Part 3",
                            PartNumber = 3,
                            Skill = 1
                        },
                        new
                        {
                            PartId = 14,
                            Description = "Speaking – Respond to questions using information provided",
                            Name = "Part 4",
                            PartNumber = 4,
                            Skill = 1
                        },
                        new
                        {
                            PartId = 15,
                            Description = "Speaking – Express an opinion",
                            Name = "Part 5",
                            PartNumber = 5,
                            Skill = 1
                        });
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionGroupId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("QuestionId");

                    b.HasIndex("PartId");

                    b.HasIndex("QuestionGroupId");

                    b.HasIndex("QuestionTypeId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 2,
                            Content = "Single Question 2",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4684),
                            Number = 2,
                            PartId = 1,
                            QuestionTypeId = 1,
                            Status = 1
                        },
                        new
                        {
                            QuestionId = 3,
                            Content = "Single Question 3",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4692),
                            Number = 3,
                            PartId = 2,
                            QuestionTypeId = 2,
                            Status = 1
                        },
                        new
                        {
                            QuestionId = 4,
                            Content = "Single Question 4",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4694),
                            Number = 4,
                            PartId = 2,
                            QuestionTypeId = 2,
                            Status = 1
                        },
                        new
                        {
                            QuestionId = 5,
                            Content = "Single Question 5",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4695),
                            Number = 5,
                            PartId = 1,
                            QuestionTypeId = 1,
                            Status = 1
                        },
                        new
                        {
                            QuestionId = 6,
                            Content = "Single Question 6",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4696),
                            Number = 6,
                            PartId = 1,
                            QuestionTypeId = 1,
                            Status = 1
                        },
                        new
                        {
                            QuestionId = 7,
                            Content = "Single Question 7",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4697),
                            Number = 7,
                            PartId = 2,
                            QuestionTypeId = 2,
                            Status = 1
                        },
                        new
                        {
                            QuestionId = 8,
                            Content = "Single Question 8",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4698),
                            Number = 8,
                            PartId = 2,
                            QuestionTypeId = 2,
                            Status = 1
                        },
                        new
                        {
                            QuestionId = 9,
                            Content = "Single Question 9",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4699),
                            Number = 9,
                            PartId = 1,
                            QuestionTypeId = 1,
                            Status = 1
                        },
                        new
                        {
                            QuestionId = 10,
                            Content = "Single Question 10",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4700),
                            Number = 10,
                            PartId = 1,
                            QuestionTypeId = 1,
                            Status = 1
                        },
                        new
                        {
                            QuestionId = 11,
                            Content = "Group 1 - Question 1",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4730),
                            Number = 1,
                            PartId = 1,
                            QuestionGroupId = 1,
                            QuestionTypeId = 1,
                            Status = 1
                        },
                        new
                        {
                            QuestionId = 12,
                            Content = "Group 1 - Question 2",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4731),
                            Number = 2,
                            PartId = 1,
                            QuestionGroupId = 1,
                            QuestionTypeId = 1,
                            Status = 1
                        },
                        new
                        {
                            QuestionId = 13,
                            Content = "Group 1 - Question 3",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4732),
                            Number = 3,
                            PartId = 1,
                            QuestionGroupId = 1,
                            QuestionTypeId = 1,
                            Status = 1
                        },
                        new
                        {
                            QuestionId = 14,
                            Content = "Group 2 - Question 1",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4733),
                            Number = 1,
                            PartId = 2,
                            QuestionGroupId = 2,
                            QuestionTypeId = 2,
                            Status = 1
                        },
                        new
                        {
                            QuestionId = 15,
                            Content = "Group 2 - Question 2",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4734),
                            Number = 2,
                            PartId = 2,
                            QuestionGroupId = 2,
                            QuestionTypeId = 2,
                            Status = 1
                        },
                        new
                        {
                            QuestionId = 16,
                            Content = "Group 2 - Question 3",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4736),
                            Number = 3,
                            PartId = 2,
                            QuestionGroupId = 2,
                            QuestionTypeId = 2,
                            Status = 1
                        },
                        new
                        {
                            QuestionId = 17,
                            Content = "Group 3 - Question 1",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4737),
                            Number = 1,
                            PartId = 1,
                            QuestionGroupId = 3,
                            QuestionTypeId = 1,
                            Status = 1
                        },
                        new
                        {
                            QuestionId = 18,
                            Content = "Group 3 - Question 2",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4738),
                            Number = 2,
                            PartId = 1,
                            QuestionGroupId = 3,
                            QuestionTypeId = 1,
                            Status = 1
                        },
                        new
                        {
                            QuestionId = 19,
                            Content = "Group 3 - Question 3",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4739),
                            Number = 3,
                            PartId = 1,
                            QuestionGroupId = 3,
                            QuestionTypeId = 1,
                            Status = 1
                        },
                        new
                        {
                            QuestionId = 1,
                            Content = "What is the capital of France?",
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4774),
                            Number = 1,
                            PartId = 1,
                            QuestionTypeId = 1,
                            Status = 1
                        });
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.QuestionGroup", b =>
                {
                    b.Property<int>("QuestionGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionGroupId"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<string>("PassageContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("QuestionGroupId");

                    b.HasIndex("PartId");

                    b.ToTable("QuestionGroups");

                    b.HasData(
                        new
                        {
                            QuestionGroupId = 1,
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4652),
                            OrderIndex = 0,
                            PartId = 6,
                            PassageContent = "Passage1",
                            Status = 1
                        },
                        new
                        {
                            QuestionGroupId = 2,
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4654),
                            OrderIndex = 0,
                            PartId = 7,
                            PassageContent = "Passage2",
                            Status = 1
                        },
                        new
                        {
                            QuestionGroupId = 3,
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 571, DateTimeKind.Utc).AddTicks(4655),
                            OrderIndex = 0,
                            PartId = 7,
                            PassageContent = "Passage3",
                            Status = 1
                        });
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.QuestionType", b =>
                {
                    b.Property<int>("QuestionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionTypeId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<int>("Skill")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionTypeId");

                    b.HasIndex("PartId");

                    b.ToTable("QuestionTypes");

                    b.HasData(
                        new
                        {
                            QuestionTypeId = 1,
                            Description = "MCQ",
                            PartId = 1,
                            Skill = 0,
                            TypeName = "[P1] Tranh tả người (Hành động/Trạng thái)"
                        },
                        new
                        {
                            QuestionTypeId = 2,
                            Description = "MCQ",
                            PartId = 1,
                            Skill = 0,
                            TypeName = "[P1] Tranh tả vật/Phong cảnh (Vị trí/Trạng thái tĩnh)"
                        },
                        new
                        {
                            QuestionTypeId = 3,
                            Description = "MCQ",
                            PartId = 1,
                            Skill = 0,
                            TypeName = "[P1] Tranh tả vật đang được thực hiện (Bị động tiếp diễn)"
                        },
                        new
                        {
                            QuestionTypeId = 4,
                            Description = "MCQ",
                            PartId = 2,
                            Skill = 0,
                            TypeName = "[P2] Câu hỏi W/H (Who, What, When, Where, Why, How)"
                        },
                        new
                        {
                            QuestionTypeId = 5,
                            Description = "MCQ",
                            PartId = 2,
                            Skill = 0,
                            TypeName = "[P2] Câu hỏi YES/NO"
                        },
                        new
                        {
                            QuestionTypeId = 6,
                            Description = "MCQ",
                            PartId = 2,
                            Skill = 0,
                            TypeName = "[P2] Câu hỏi lựa chọn (OR Question)"
                        },
                        new
                        {
                            QuestionTypeId = 7,
                            Description = "MCQ",
                            PartId = 2,
                            Skill = 0,
                            TypeName = "[P2] Câu hỏi đuôi / Xác nhận (Tag/Negative Questions)"
                        },
                        new
                        {
                            QuestionTypeId = 8,
                            Description = "MCQ",
                            PartId = 2,
                            Skill = 0,
                            TypeName = "[P2] Câu yêu cầu, đề nghị, gợi ý (Request/Suggestion)"
                        },
                        new
                        {
                            QuestionTypeId = 9,
                            Description = "MCQ",
                            PartId = 2,
                            Skill = 0,
                            TypeName = "[P2] Câu trần thuật (Statement/Response)"
                        },
                        new
                        {
                            QuestionTypeId = 10,
                            Description = "MCQ",
                            PartId = 3,
                            Skill = 0,
                            TypeName = "[P3] Hỏi về ý chính/Mục đích hội thoại (Purpose/Gist)"
                        },
                        new
                        {
                            QuestionTypeId = 11,
                            Description = "MCQ",
                            PartId = 3,
                            Skill = 0,
                            TypeName = "[P3] Hỏi chi tiết thông tin được đề cập (Detail)"
                        },
                        new
                        {
                            QuestionTypeId = 12,
                            Description = "MCQ",
                            PartId = 3,
                            Skill = 0,
                            TypeName = "[P3] Hỏi về hành động tiếp theo (Action/Do-next)"
                        },
                        new
                        {
                            QuestionTypeId = 13,
                            Description = "MCQ",
                            PartId = 3,
                            Skill = 0,
                            TypeName = "[P3] Hỏi suy luận/Ý định/Thái độ (Inference/Attitude)"
                        },
                        new
                        {
                            QuestionTypeId = 14,
                            Description = "MCQ",
                            PartId = 3,
                            Skill = 0,
                            TypeName = "[P3] Hỏi dựa vào Hình/Bảng dữ liệu (Graphic Question)"
                        },
                        new
                        {
                            QuestionTypeId = 15,
                            Description = "MCQ",
                            PartId = 4,
                            Skill = 0,
                            TypeName = "[P4] Hỏi nội dung chính/Chủ đề bài nói (Main Topic)"
                        },
                        new
                        {
                            QuestionTypeId = 16,
                            Description = "MCQ",
                            PartId = 4,
                            Skill = 0,
                            TypeName = "[P4] Hỏi chi tiết thông tin được đề cập (Detail)"
                        },
                        new
                        {
                            QuestionTypeId = 17,
                            Description = "MCQ",
                            PartId = 4,
                            Skill = 0,
                            TypeName = "[P4] Hỏi suy luận/Hàm ý (Inference/Imply)"
                        },
                        new
                        {
                            QuestionTypeId = 18,
                            Description = "MCQ",
                            PartId = 4,
                            Skill = 0,
                            TypeName = "[P4] Hỏi hành động người nghe nên làm (Listener Action)"
                        },
                        new
                        {
                            QuestionTypeId = 19,
                            Description = "MCQ",
                            PartId = 4,
                            Skill = 0,
                            TypeName = "[P4] Hỏi dựa vào Hình/Bảng dữ liệu (Graphic Question)"
                        },
                        new
                        {
                            QuestionTypeId = 20,
                            Description = "MCQ",
                            PartId = 5,
                            Skill = 0,
                            TypeName = "[P5] Ngữ pháp (Thì, Câu điều kiện, Liên từ, Giới từ,...) "
                        },
                        new
                        {
                            QuestionTypeId = 21,
                            Description = "MCQ",
                            PartId = 5,
                            Skill = 0,
                            TypeName = "[P5] Từ loại (N, V, Adj, Adv)"
                        },
                        new
                        {
                            QuestionTypeId = 22,
                            Description = "MCQ",
                            PartId = 5,
                            Skill = 0,
                            TypeName = "[P5] Từ vựng (Nghĩa của từ)"
                        },
                        new
                        {
                            QuestionTypeId = 23,
                            Description = "MCQ",
                            PartId = 6,
                            Skill = 0,
                            TypeName = "[P6] Hoàn thành câu/Từ loại/Từ vựng trong đoạn văn"
                        },
                        new
                        {
                            QuestionTypeId = 24,
                            Description = "MCQ",
                            PartId = 6,
                            Skill = 0,
                            TypeName = "[P6] Chọn câu phù hợp để điền vào chỗ trống"
                        },
                        new
                        {
                            QuestionTypeId = 25,
                            Description = "MCQ",
                            PartId = 7,
                            Skill = 0,
                            TypeName = "[P7] Hỏi về ý chính/Mục đích (Main Idea/Purpose)"
                        },
                        new
                        {
                            QuestionTypeId = 26,
                            Description = "MCQ",
                            PartId = 7,
                            Skill = 0,
                            TypeName = "[P7] Tìm thông tin chi tiết (Specific Detail)"
                        },
                        new
                        {
                            QuestionTypeId = 27,
                            Description = "MCQ",
                            PartId = 7,
                            Skill = 0,
                            TypeName = "[P7] Suy luận/Thông tin không đề cập (Inference/NOT TRUE)"
                        },
                        new
                        {
                            QuestionTypeId = 28,
                            Description = "MCQ",
                            PartId = 7,
                            Skill = 0,
                            TypeName = "[P7] Tìm từ đồng nghĩa (Synonym/Meaning)"
                        },
                        new
                        {
                            QuestionTypeId = 29,
                            Description = "MCQ",
                            PartId = 7,
                            Skill = 0,
                            TypeName = "[P7] Thêm câu vào chỗ trống (Sentence Insertion - Chỉ trong Multi-Passage)"
                        },
                        new
                        {
                            QuestionTypeId = 30,
                            Description = "MCQ",
                            PartId = 7,
                            Skill = 0,
                            TypeName = "[P7] Liên kết thông tin giữa các đoạn (Connecting Information)"
                        },
                        new
                        {
                            QuestionTypeId = 31,
                            Description = "ShortAnswer",
                            PartId = 11,
                            Skill = 1,
                            TypeName = "[Speaking] Đọc to đoạn văn (Read a text aloud)"
                        },
                        new
                        {
                            QuestionTypeId = 32,
                            Description = "ShortAnswer",
                            PartId = 12,
                            Skill = 1,
                            TypeName = "[Speaking] Mô tả tranh (Describe a picture)"
                        },
                        new
                        {
                            QuestionTypeId = 33,
                            Description = "ShortAnswer",
                            PartId = 13,
                            Skill = 1,
                            TypeName = "[Speaking] Trả lời câu hỏi cá nhân (Respond to questions Q5-7)"
                        },
                        new
                        {
                            QuestionTypeId = 34,
                            Description = "ShortAnswer",
                            PartId = 14,
                            Skill = 1,
                            TypeName = "[Speaking] Trả lời dựa vào bảng/lịch (Respond to questions Q8-10)"
                        },
                        new
                        {
                            QuestionTypeId = 35,
                            Description = "ShortAnswer",
                            PartId = 15,
                            Skill = 1,
                            TypeName = "[Speaking] Bày tỏ ý kiến cá nhân (Express an opinion Q11)"
                        },
                        new
                        {
                            QuestionTypeId = 36,
                            Description = "Essay",
                            PartId = 8,
                            Skill = 2,
                            TypeName = "[Writing] Viết câu dựa vào tranh (Write a sentence Q1-5)"
                        },
                        new
                        {
                            QuestionTypeId = 37,
                            Description = "Essay",
                            PartId = 9,
                            Skill = 2,
                            TypeName = "[Writing] Viết thư trả lời yêu cầu (Respond to a written request Q6-7)"
                        },
                        new
                        {
                            QuestionTypeId = 38,
                            Description = "Essay",
                            PartId = 10,
                            Skill = 2,
                            TypeName = "[Writing] Viết luận nêu ý kiến cá nhân (Write an opinion essay Q8)"
                        });
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("RevokeAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokeByIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Examinee"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "TestCreator"
                        });
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestId"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int?>("PartId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TestSkill")
                        .HasColumnType("int");

                    b.Property<int>("TestType")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TestId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PartId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.TestQuestion", b =>
                {
                    b.Property<int>("TestQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestQuestionId"));

                    b.Property<int>("OrderInTest")
                        .HasColumnType("int");

                    b.Property<int?>("OriginalQuestionGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("OriginalQuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("PartId")
                        .HasColumnType("int");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("TestQuestionId");

                    b.HasIndex("PartId");

                    b.HasIndex("TestId");

                    b.ToTable("TestQuestion");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.TestResult", b =>
                {
                    b.Property<int>("UserTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserTestId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<string>("TestMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserTestId");

                    b.HasIndex("TestId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTests");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 688, DateTimeKind.Utc).AddTicks(7967),
                            Email = "admin@toeicgenius.com",
                            FullName = "System Admin",
                            PasswordHash = "$2a$11$VV9ETAQ.wX3fVob2IIAi6eWSSgEh9hYdKzoF5KaUTRh61WP4RdqmW",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 808, DateTimeKind.Utc).AddTicks(4449),
                            Email = "creator@toeicgenius.com",
                            FullName = "Test Creator",
                            PasswordHash = "$2a$11$I8av6Kz5Ce/1R.qizf1hyebrCkF6D/qJ6QERXC6zCJkR/4LDSxuAi",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 10, 18, 3, 24, 3, 924, DateTimeKind.Utc).AddTicks(7400),
                            Email = "examinee@toeicgenius.com",
                            FullName = "Regular Examinee",
                            PasswordHash = "$2a$11$Y2WySfr46yhh4On3kZRdkeNzlTVHROkvzQgaV4YGDzwdL1IHWJKI6",
                            Status = 1
                        });
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.UserAnswer", b =>
                {
                    b.Property<int>("UserAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAnswerId"));

                    b.Property<string>("AnswerAudioUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OptionId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserTestId")
                        .HasColumnType("int");

                    b.HasKey("UserAnswerId");

                    b.HasIndex("OptionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserTestId");

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.UserOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtpCodeHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UserOtps");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.UserTestSkillScore", b =>
                {
                    b.Property<int>("UserTestResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserTestResultId"));

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Skill")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserTestId")
                        .HasColumnType("int");

                    b.HasKey("UserTestResultId");

                    b.HasIndex("UserTestId");

                    b.ToTable("UserTestSkillScores");
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoleId = 1
                        },
                        new
                        {
                            UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RoleId = 3
                        },
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.AIFeedback", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.UserAnswer", "UserAnswer")
                        .WithMany()
                        .HasForeignKey("UserAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAnswer");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Flashcard", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.FlashcardSet", "FlashcardSet")
                        .WithMany("Flashcards")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlashcardSet");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.FlashcardProgress", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.Flashcard", "Flashcard")
                        .WithMany("Progresses")
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flashcard");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.FlashcardSet", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Option", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Question", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.Part", "Part")
                        .WithMany("Questions")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ToeicGenius.Domains.Entities.QuestionGroup", "QuestionGroup")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionGroupId");

                    b.HasOne("ToeicGenius.Domains.Entities.QuestionType", "QuestionType")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("QuestionGroup");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.QuestionGroup", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.Part", "Part")
                        .WithMany("QuestionGroups")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.QuestionType", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.Part", "Part")
                        .WithMany("QuestionTypes")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.RefreshToken", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Test", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ToeicGenius.Domains.Entities.Part", null)
                        .WithMany("Tests")
                        .HasForeignKey("PartId");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.TestQuestion", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ToeicGenius.Domains.Entities.Test", "Test")
                        .WithMany("TestQuestions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.TestResult", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.Test", "Test")
                        .WithMany("TestResults")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToeicGenius.Domains.Entities.User", "User")
                        .WithMany("UserTests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.UserAnswer", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.Option", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId");

                    b.HasOne("ToeicGenius.Domains.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToeicGenius.Domains.Entities.TestResult", "UserTest")
                        .WithMany("UserAnswers")
                        .HasForeignKey("UserTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");

                    b.Navigation("Question");

                    b.Navigation("UserTest");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.UserTestSkillScore", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.TestResult", "UserTest")
                        .WithMany("SkillScores")
                        .HasForeignKey("UserTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserTest");
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.HasOne("ToeicGenius.Domains.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToeicGenius.Domains.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Flashcard", b =>
                {
                    b.Navigation("Progresses");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.FlashcardSet", b =>
                {
                    b.Navigation("Flashcards");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Part", b =>
                {
                    b.Navigation("QuestionGroups");

                    b.Navigation("QuestionTypes");

                    b.Navigation("Questions");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.QuestionGroup", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.QuestionType", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.Test", b =>
                {
                    b.Navigation("TestQuestions");

                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.TestResult", b =>
                {
                    b.Navigation("SkillScores");

                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("ToeicGenius.Domains.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserTests");
                });
#pragma warning restore 612, 618
        }
    }
}
